version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql_eb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./projet
    container_name: app_eb
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password

volumes:
  mysql_data:
